version: "3"
services:
  ddns:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddns
    dns:
      - 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./ddns:/config
    restart: unless-stopped
    ports:
      - "8080:80/tcp"

  nginx:
    container_name: nginx
    image: nginx:alpine
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
